error: conflicting call name `my_int`
   ┌─ tests/analysis/conflicting-call-names/source.wdl:25:10
   │
24 │     Int my_int = 0      # FIRST
   │         ------ the declaration with the conflicting name is here
25 │     call my_int         # NOT OK
   │          ^^^^^^ this call name conflicts with a previously used name
   │
   = fix: add an `as` clause to the call to specify a different name

error: conflicting call name `foo`
   ┌─ tests/analysis/conflicting-call-names/source.wdl:28:10
   │
27 │     call foo            # FIRST
   │          --- the call with the conflicting name is here
28 │     call foo            # NOT OK
   │          ^^^ this call name conflicts with a previously used name
   │
   = fix: add an `as` clause to the call to specify a different name

error: conflicting call name `bar`
   ┌─ tests/analysis/conflicting-call-names/source.wdl:31:17
   │
30 │     call foo as bar     # FIRST
   │                 --- the call with the conflicting name is here
31 │     call foo as bar     # NOT OK
   │                 ^^^ this call name conflicts with a previously used name

error: conflicting call name `bar`
   ┌─ tests/analysis/conflicting-call-names/source.wdl:33:10
   │
30 │     call foo as bar     # FIRST
   │                 --- the call with the conflicting name is here
   ·
33 │     call bar            # NOT OK
   │          ^^^ this call name conflicts with a previously used name
   │
   = fix: add an `as` clause to the call to specify a different name

error: conflicting call name `bar`
   ┌─ tests/analysis/conflicting-call-names/source.wdl:35:14
   │
30 │     call foo as bar     # FIRST
   │                 --- the call with the conflicting name is here
   ·
35 │     call baz.bar        # NOT OK
   │              ^^^ this call name conflicts with a previously used name
   │
   = fix: add an `as` clause to the call to specify a different name

error: conflicting call name `baz`
   ┌─ tests/analysis/conflicting-call-names/source.wdl:38:17
   │
36 │     call baz.baz        # FIRST
   │              --- the call with the conflicting name is here
37 │ 
38 │     call foo as baz     # NOT OK
   │                 ^^^ this call name conflicts with a previously used name

error: conflicting call name `foo`
   ┌─ tests/analysis/conflicting-call-names/source.wdl:41:14
   │
27 │     call foo            # FIRST
   │          --- the call with the conflicting name is here
   ·
41 │         call foo        # NOT OK
   │              ^^^ this call name conflicts with a previously used name
   │
   = fix: add an `as` clause to the call to specify a different name

error: conflicting call name `x`
   ┌─ tests/analysis/conflicting-call-names/source.wdl:42:14
   │
40 │     scatter (x in []) {
   │              - the scatter variable with the conflicting name is here
41 │         call foo        # NOT OK
42 │         call x          # NOT OK
   │              ^ this call name conflicts with a previously used name
   │
   = fix: add an `as` clause to the call to specify a different name

error: conflicting call name `x`
   ┌─ tests/analysis/conflicting-call-names/source.wdl:46:10
   │
42 │         call x          # NOT OK
   │              - the call with the conflicting name is here
   ·
46 │     call x              # NOT OK
   │          ^ this call name conflicts with a previously used name
   │
   = fix: add an `as` clause to the call to specify a different name

error: conflicting call name `ok`
   ┌─ tests/analysis/conflicting-call-names/source.wdl:47:10
   │
43 │         call ok         # OK
   │              -- the call with the conflicting name is here
   ·
47 │     call ok             # NOT OK
   │          ^^ this call name conflicts with a previously used name
   │
   = fix: add an `as` clause to the call to specify a different name

